### ISSUE TITLE
Generate dynamic instead of type

### ISSUE THREAD

**Issue by jaumard** [aloisdeniel/built_bloc#2]
`final BehaviorSubject _test = BehaviorSubject<bool>();` is generate to `Stream<dynamic> get msiEnabled => _parent._msiEnabled.stream;`

`final BehaviorSubject<bool> _test = BehaviorSubject();` works fine :)

**Comment by aloisdeniel** [comment]
Ah yes, the generator looks the declared type and not the instance one.

To me, all declarations should have the generic type :

```dart
final BehaviorSubject<bool> _test = BehaviorSubject<bool>();
``` 

Thanks for the report!

**Comment by rrousselGit** [comment]
Dart style explicitly specify that we should omit the variable type if it can be inferred.

There is even a linter rule that will request for the removal of the first `BehaviorSubject<bool>`

**Comment by aloisdeniel** [comment]
Hum yeah, but surely not a dynamic parameter type !

**Comment by rrousselGit** [comment]
Ah, good point. I don't think it's a bug actually, but an issue with @jaumard code

**Comment by jaumard** [comment]
I miss that rule thanks ^^ but for me it's still a bug if you consider that `BehaviorSubject _test = BehaviorSubject<bool>();` should not generate dynamic :) if not all good we can close this

**Comment by rrousselGit** [comment]
`BehaviorSubject _test = BehaviorSubject<bool>()` is syntax sugar for `BehaviorSubject<dynamic> _test = BehaviorSubject<bool>();`

The opposite is not true:

`BehaviorSubject<bool> _test = BehaviorSubject()` is a shorthand for `BehaviorSubject<bool>  _test = BehaviorSubject<bool>()

**Comment by aloisdeniel** [comment]
Just tried and the generator works for :

```dart
final _test = BehaviorSubject<bool>();
```
